/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotificationFanOutEngineIndexRouteImport } from './routes/notification-fan-out-engine/index'
import { Route as SecretFlowersIndexRouteImport } from './routes/secret/flowers/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationFanOutEngineIndexRoute =
  NotificationFanOutEngineIndexRouteImport.update({
    id: '/notification-fan-out-engine/',
    path: '/notification-fan-out-engine/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SecretFlowersIndexRoute = SecretFlowersIndexRouteImport.update({
  id: '/secret/flowers/',
  path: '/secret/flowers/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notification-fan-out-engine/': typeof NotificationFanOutEngineIndexRoute
  '/secret/flowers/': typeof SecretFlowersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notification-fan-out-engine': typeof NotificationFanOutEngineIndexRoute
  '/secret/flowers': typeof SecretFlowersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notification-fan-out-engine/': typeof NotificationFanOutEngineIndexRoute
  '/secret/flowers/': typeof SecretFlowersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notification-fan-out-engine/' | '/secret/flowers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notification-fan-out-engine' | '/secret/flowers'
  id: '__root__' | '/' | '/notification-fan-out-engine/' | '/secret/flowers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificationFanOutEngineIndexRoute: typeof NotificationFanOutEngineIndexRoute
  SecretFlowersIndexRoute: typeof SecretFlowersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-fan-out-engine/': {
      id: '/notification-fan-out-engine/'
      path: '/notification-fan-out-engine'
      fullPath: '/notification-fan-out-engine/'
      preLoaderRoute: typeof NotificationFanOutEngineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret/flowers/': {
      id: '/secret/flowers/'
      path: '/secret/flowers'
      fullPath: '/secret/flowers/'
      preLoaderRoute: typeof SecretFlowersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificationFanOutEngineIndexRoute: NotificationFanOutEngineIndexRoute,
  SecretFlowersIndexRoute: SecretFlowersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
